/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the SiteCapabilities type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SiteCapabilities{}

// SiteCapabilities Boolean flags to indicate features supported by a Site
type SiteCapabilities struct {
	NativeNetworking          *bool `json:"nativeNetworking,omitempty"`
	NetworkSecurityGroup      *bool `json:"networkSecurityGroup,omitempty"`
	NvLinkPartition           *bool `json:"nvLinkPartition,omitempty"`
	Flow                      *bool `json:"flow,omitempty"`
	ImageBasedOperatingSystem *bool `json:"imageBasedOperatingSystem,omitempty"`
}

// NewSiteCapabilities instantiates a new SiteCapabilities object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSiteCapabilities() *SiteCapabilities {
	this := SiteCapabilities{}
	return &this
}

// NewSiteCapabilitiesWithDefaults instantiates a new SiteCapabilities object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSiteCapabilitiesWithDefaults() *SiteCapabilities {
	this := SiteCapabilities{}
	return &this
}

// GetNativeNetworking returns the NativeNetworking field value if set, zero value otherwise.
func (o *SiteCapabilities) GetNativeNetworking() bool {
	if o == nil || IsNil(o.NativeNetworking) {
		var ret bool
		return ret
	}
	return *o.NativeNetworking
}

// GetNativeNetworkingOk returns a tuple with the NativeNetworking field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteCapabilities) GetNativeNetworkingOk() (*bool, bool) {
	if o == nil || IsNil(o.NativeNetworking) {
		return nil, false
	}
	return o.NativeNetworking, true
}

// HasNativeNetworking returns a boolean if a field has been set.
func (o *SiteCapabilities) HasNativeNetworking() bool {
	if o != nil && !IsNil(o.NativeNetworking) {
		return true
	}

	return false
}

// SetNativeNetworking gets a reference to the given bool and assigns it to the NativeNetworking field.
func (o *SiteCapabilities) SetNativeNetworking(v bool) {
	o.NativeNetworking = &v
}

// GetNetworkSecurityGroup returns the NetworkSecurityGroup field value if set, zero value otherwise.
func (o *SiteCapabilities) GetNetworkSecurityGroup() bool {
	if o == nil || IsNil(o.NetworkSecurityGroup) {
		var ret bool
		return ret
	}
	return *o.NetworkSecurityGroup
}

// GetNetworkSecurityGroupOk returns a tuple with the NetworkSecurityGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteCapabilities) GetNetworkSecurityGroupOk() (*bool, bool) {
	if o == nil || IsNil(o.NetworkSecurityGroup) {
		return nil, false
	}
	return o.NetworkSecurityGroup, true
}

// HasNetworkSecurityGroup returns a boolean if a field has been set.
func (o *SiteCapabilities) HasNetworkSecurityGroup() bool {
	if o != nil && !IsNil(o.NetworkSecurityGroup) {
		return true
	}

	return false
}

// SetNetworkSecurityGroup gets a reference to the given bool and assigns it to the NetworkSecurityGroup field.
func (o *SiteCapabilities) SetNetworkSecurityGroup(v bool) {
	o.NetworkSecurityGroup = &v
}

// GetNvLinkPartition returns the NvLinkPartition field value if set, zero value otherwise.
func (o *SiteCapabilities) GetNvLinkPartition() bool {
	if o == nil || IsNil(o.NvLinkPartition) {
		var ret bool
		return ret
	}
	return *o.NvLinkPartition
}

// GetNvLinkPartitionOk returns a tuple with the NvLinkPartition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteCapabilities) GetNvLinkPartitionOk() (*bool, bool) {
	if o == nil || IsNil(o.NvLinkPartition) {
		return nil, false
	}
	return o.NvLinkPartition, true
}

// HasNvLinkPartition returns a boolean if a field has been set.
func (o *SiteCapabilities) HasNvLinkPartition() bool {
	if o != nil && !IsNil(o.NvLinkPartition) {
		return true
	}

	return false
}

// SetNvLinkPartition gets a reference to the given bool and assigns it to the NvLinkPartition field.
func (o *SiteCapabilities) SetNvLinkPartition(v bool) {
	o.NvLinkPartition = &v
}

// GetFlow returns the Flow field value if set, zero value otherwise.
func (o *SiteCapabilities) GetFlow() bool {
	if o == nil || IsNil(o.Flow) {
		var ret bool
		return ret
	}
	return *o.Flow
}

// GetFlowOk returns a tuple with the Flow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteCapabilities) GetFlowOk() (*bool, bool) {
	if o == nil || IsNil(o.Flow) {
		return nil, false
	}
	return o.Flow, true
}

// HasFlow returns a boolean if a field has been set.
func (o *SiteCapabilities) HasFlow() bool {
	if o != nil && !IsNil(o.Flow) {
		return true
	}

	return false
}

// SetFlow gets a reference to the given bool and assigns it to the Flow field.
func (o *SiteCapabilities) SetFlow(v bool) {
	o.Flow = &v
}

// GetImageBasedOperatingSystem returns the ImageBasedOperatingSystem field value if set, zero value otherwise.
func (o *SiteCapabilities) GetImageBasedOperatingSystem() bool {
	if o == nil || IsNil(o.ImageBasedOperatingSystem) {
		var ret bool
		return ret
	}
	return *o.ImageBasedOperatingSystem
}

// GetImageBasedOperatingSystemOk returns a tuple with the ImageBasedOperatingSystem field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteCapabilities) GetImageBasedOperatingSystemOk() (*bool, bool) {
	if o == nil || IsNil(o.ImageBasedOperatingSystem) {
		return nil, false
	}
	return o.ImageBasedOperatingSystem, true
}

// HasImageBasedOperatingSystem returns a boolean if a field has been set.
func (o *SiteCapabilities) HasImageBasedOperatingSystem() bool {
	if o != nil && !IsNil(o.ImageBasedOperatingSystem) {
		return true
	}

	return false
}

// SetImageBasedOperatingSystem gets a reference to the given bool and assigns it to the ImageBasedOperatingSystem field.
func (o *SiteCapabilities) SetImageBasedOperatingSystem(v bool) {
	o.ImageBasedOperatingSystem = &v
}

func (o SiteCapabilities) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SiteCapabilities) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NativeNetworking) {
		toSerialize["nativeNetworking"] = o.NativeNetworking
	}
	if !IsNil(o.NetworkSecurityGroup) {
		toSerialize["networkSecurityGroup"] = o.NetworkSecurityGroup
	}
	if !IsNil(o.NvLinkPartition) {
		toSerialize["nvLinkPartition"] = o.NvLinkPartition
	}
	if !IsNil(o.Flow) {
		toSerialize["flow"] = o.Flow
	}
	if !IsNil(o.ImageBasedOperatingSystem) {
		toSerialize["imageBasedOperatingSystem"] = o.ImageBasedOperatingSystem
	}
	return toSerialize, nil
}

type NullableSiteCapabilities struct {
	value *SiteCapabilities
	isSet bool
}

func (v NullableSiteCapabilities) Get() *SiteCapabilities {
	return v.value
}

func (v *NullableSiteCapabilities) Set(val *SiteCapabilities) {
	v.value = val
	v.isSet = true
}

func (v NullableSiteCapabilities) IsSet() bool {
	return v.isSet
}

func (v *NullableSiteCapabilities) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSiteCapabilities(val *SiteCapabilities) *NullableSiteCapabilities {
	return &NullableSiteCapabilities{value: val, isSet: true}
}

func (v NullableSiteCapabilities) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSiteCapabilities) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
