/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the ComponentDiff type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComponentDiff{}

// ComponentDiff A single component difference found during rack validation
type ComponentDiff struct {
	// Type of difference: Unknown, Missing, Unexpected, or Drift
	Type *string `json:"type,omitempty"`
	// Flow internal component UUID
	Id *string `json:"id,omitempty"`
	// Component ID assigned by the component manager service
	ComponentId *string        `json:"componentId,omitempty"`
	Expected    *RackComponent `json:"expected,omitempty"`
	Actual      *RackComponent `json:"actual,omitempty"`
	// List of field differences (populated when type is DiffTypeDrift)
	FieldDiffs []FieldDiff `json:"fieldDiffs,omitempty"`
}

// NewComponentDiff instantiates a new ComponentDiff object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComponentDiff() *ComponentDiff {
	this := ComponentDiff{}
	return &this
}

// NewComponentDiffWithDefaults instantiates a new ComponentDiff object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComponentDiffWithDefaults() *ComponentDiff {
	this := ComponentDiff{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ComponentDiff) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComponentDiff) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ComponentDiff) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ComponentDiff) SetType(v string) {
	o.Type = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ComponentDiff) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComponentDiff) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ComponentDiff) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ComponentDiff) SetId(v string) {
	o.Id = &v
}

// GetComponentId returns the ComponentId field value if set, zero value otherwise.
func (o *ComponentDiff) GetComponentId() string {
	if o == nil || IsNil(o.ComponentId) {
		var ret string
		return ret
	}
	return *o.ComponentId
}

// GetComponentIdOk returns a tuple with the ComponentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComponentDiff) GetComponentIdOk() (*string, bool) {
	if o == nil || IsNil(o.ComponentId) {
		return nil, false
	}
	return o.ComponentId, true
}

// HasComponentId returns a boolean if a field has been set.
func (o *ComponentDiff) HasComponentId() bool {
	if o != nil && !IsNil(o.ComponentId) {
		return true
	}

	return false
}

// SetComponentId gets a reference to the given string and assigns it to the ComponentId field.
func (o *ComponentDiff) SetComponentId(v string) {
	o.ComponentId = &v
}

// GetExpected returns the Expected field value if set, zero value otherwise.
func (o *ComponentDiff) GetExpected() RackComponent {
	if o == nil || IsNil(o.Expected) {
		var ret RackComponent
		return ret
	}
	return *o.Expected
}

// GetExpectedOk returns a tuple with the Expected field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComponentDiff) GetExpectedOk() (*RackComponent, bool) {
	if o == nil || IsNil(o.Expected) {
		return nil, false
	}
	return o.Expected, true
}

// HasExpected returns a boolean if a field has been set.
func (o *ComponentDiff) HasExpected() bool {
	if o != nil && !IsNil(o.Expected) {
		return true
	}

	return false
}

// SetExpected gets a reference to the given RackComponent and assigns it to the Expected field.
func (o *ComponentDiff) SetExpected(v RackComponent) {
	o.Expected = &v
}

// GetActual returns the Actual field value if set, zero value otherwise.
func (o *ComponentDiff) GetActual() RackComponent {
	if o == nil || IsNil(o.Actual) {
		var ret RackComponent
		return ret
	}
	return *o.Actual
}

// GetActualOk returns a tuple with the Actual field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComponentDiff) GetActualOk() (*RackComponent, bool) {
	if o == nil || IsNil(o.Actual) {
		return nil, false
	}
	return o.Actual, true
}

// HasActual returns a boolean if a field has been set.
func (o *ComponentDiff) HasActual() bool {
	if o != nil && !IsNil(o.Actual) {
		return true
	}

	return false
}

// SetActual gets a reference to the given RackComponent and assigns it to the Actual field.
func (o *ComponentDiff) SetActual(v RackComponent) {
	o.Actual = &v
}

// GetFieldDiffs returns the FieldDiffs field value if set, zero value otherwise.
func (o *ComponentDiff) GetFieldDiffs() []FieldDiff {
	if o == nil || IsNil(o.FieldDiffs) {
		var ret []FieldDiff
		return ret
	}
	return o.FieldDiffs
}

// GetFieldDiffsOk returns a tuple with the FieldDiffs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComponentDiff) GetFieldDiffsOk() ([]FieldDiff, bool) {
	if o == nil || IsNil(o.FieldDiffs) {
		return nil, false
	}
	return o.FieldDiffs, true
}

// HasFieldDiffs returns a boolean if a field has been set.
func (o *ComponentDiff) HasFieldDiffs() bool {
	if o != nil && !IsNil(o.FieldDiffs) {
		return true
	}

	return false
}

// SetFieldDiffs gets a reference to the given []FieldDiff and assigns it to the FieldDiffs field.
func (o *ComponentDiff) SetFieldDiffs(v []FieldDiff) {
	o.FieldDiffs = v
}

func (o ComponentDiff) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComponentDiff) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.ComponentId) {
		toSerialize["componentId"] = o.ComponentId
	}
	if !IsNil(o.Expected) {
		toSerialize["expected"] = o.Expected
	}
	if !IsNil(o.Actual) {
		toSerialize["actual"] = o.Actual
	}
	if !IsNil(o.FieldDiffs) {
		toSerialize["fieldDiffs"] = o.FieldDiffs
	}
	return toSerialize, nil
}

type NullableComponentDiff struct {
	value *ComponentDiff
	isSet bool
}

func (v NullableComponentDiff) Get() *ComponentDiff {
	return v.value
}

func (v *NullableComponentDiff) Set(val *ComponentDiff) {
	v.value = val
	v.isSet = true
}

func (v NullableComponentDiff) IsSet() bool {
	return v.isSet
}

func (v *NullableComponentDiff) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComponentDiff(val *ComponentDiff) *NullableComponentDiff {
	return &NullableComponentDiff{value: val, isSet: true}
}

func (v NullableComponentDiff) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComponentDiff) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
