/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the SiteCapabilitiesUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SiteCapabilitiesUpdateRequest{}

// SiteCapabilitiesUpdateRequest Request to modify Site's capabilities. Partial update allowed, only specify capabilities that should be updated.
type SiteCapabilitiesUpdateRequest struct {
	// Enable or disable native networking for the Site
	NativeNetworking NullableBool `json:"nativeNetworking,omitempty"`
	// Enable or disable network security groups for the Site
	NetworkSecurityGroup NullableBool `json:"networkSecurityGroup,omitempty"`
	// Enable or disable NVLink partition support for the Site
	NvLinkPartition NullableBool `json:"nvLinkPartition,omitempty"`
	// Enable or disable NICo Flow for the Site
	Flow NullableBool `json:"flow,omitempty"`
	// Enable or disable image-based operating system support for the Site
	ImageBasedOperatingSystem NullableBool `json:"imageBasedOperatingSystem,omitempty"`
}

// NewSiteCapabilitiesUpdateRequest instantiates a new SiteCapabilitiesUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSiteCapabilitiesUpdateRequest() *SiteCapabilitiesUpdateRequest {
	this := SiteCapabilitiesUpdateRequest{}
	return &this
}

// NewSiteCapabilitiesUpdateRequestWithDefaults instantiates a new SiteCapabilitiesUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSiteCapabilitiesUpdateRequestWithDefaults() *SiteCapabilitiesUpdateRequest {
	this := SiteCapabilitiesUpdateRequest{}
	return &this
}

// GetNativeNetworking returns the NativeNetworking field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SiteCapabilitiesUpdateRequest) GetNativeNetworking() bool {
	if o == nil || IsNil(o.NativeNetworking.Get()) {
		var ret bool
		return ret
	}
	return *o.NativeNetworking.Get()
}

// GetNativeNetworkingOk returns a tuple with the NativeNetworking field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SiteCapabilitiesUpdateRequest) GetNativeNetworkingOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.NativeNetworking.Get(), o.NativeNetworking.IsSet()
}

// HasNativeNetworking returns a boolean if a field has been set.
func (o *SiteCapabilitiesUpdateRequest) HasNativeNetworking() bool {
	if o != nil && o.NativeNetworking.IsSet() {
		return true
	}

	return false
}

// SetNativeNetworking gets a reference to the given NullableBool and assigns it to the NativeNetworking field.
func (o *SiteCapabilitiesUpdateRequest) SetNativeNetworking(v bool) {
	o.NativeNetworking.Set(&v)
}

// SetNativeNetworkingNil sets the value for NativeNetworking to be an explicit nil
func (o *SiteCapabilitiesUpdateRequest) SetNativeNetworkingNil() {
	o.NativeNetworking.Set(nil)
}

// UnsetNativeNetworking ensures that no value is present for NativeNetworking, not even an explicit nil
func (o *SiteCapabilitiesUpdateRequest) UnsetNativeNetworking() {
	o.NativeNetworking.Unset()
}

// GetNetworkSecurityGroup returns the NetworkSecurityGroup field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SiteCapabilitiesUpdateRequest) GetNetworkSecurityGroup() bool {
	if o == nil || IsNil(o.NetworkSecurityGroup.Get()) {
		var ret bool
		return ret
	}
	return *o.NetworkSecurityGroup.Get()
}

// GetNetworkSecurityGroupOk returns a tuple with the NetworkSecurityGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SiteCapabilitiesUpdateRequest) GetNetworkSecurityGroupOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.NetworkSecurityGroup.Get(), o.NetworkSecurityGroup.IsSet()
}

// HasNetworkSecurityGroup returns a boolean if a field has been set.
func (o *SiteCapabilitiesUpdateRequest) HasNetworkSecurityGroup() bool {
	if o != nil && o.NetworkSecurityGroup.IsSet() {
		return true
	}

	return false
}

// SetNetworkSecurityGroup gets a reference to the given NullableBool and assigns it to the NetworkSecurityGroup field.
func (o *SiteCapabilitiesUpdateRequest) SetNetworkSecurityGroup(v bool) {
	o.NetworkSecurityGroup.Set(&v)
}

// SetNetworkSecurityGroupNil sets the value for NetworkSecurityGroup to be an explicit nil
func (o *SiteCapabilitiesUpdateRequest) SetNetworkSecurityGroupNil() {
	o.NetworkSecurityGroup.Set(nil)
}

// UnsetNetworkSecurityGroup ensures that no value is present for NetworkSecurityGroup, not even an explicit nil
func (o *SiteCapabilitiesUpdateRequest) UnsetNetworkSecurityGroup() {
	o.NetworkSecurityGroup.Unset()
}

// GetNvLinkPartition returns the NvLinkPartition field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SiteCapabilitiesUpdateRequest) GetNvLinkPartition() bool {
	if o == nil || IsNil(o.NvLinkPartition.Get()) {
		var ret bool
		return ret
	}
	return *o.NvLinkPartition.Get()
}

// GetNvLinkPartitionOk returns a tuple with the NvLinkPartition field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SiteCapabilitiesUpdateRequest) GetNvLinkPartitionOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.NvLinkPartition.Get(), o.NvLinkPartition.IsSet()
}

// HasNvLinkPartition returns a boolean if a field has been set.
func (o *SiteCapabilitiesUpdateRequest) HasNvLinkPartition() bool {
	if o != nil && o.NvLinkPartition.IsSet() {
		return true
	}

	return false
}

// SetNvLinkPartition gets a reference to the given NullableBool and assigns it to the NvLinkPartition field.
func (o *SiteCapabilitiesUpdateRequest) SetNvLinkPartition(v bool) {
	o.NvLinkPartition.Set(&v)
}

// SetNvLinkPartitionNil sets the value for NvLinkPartition to be an explicit nil
func (o *SiteCapabilitiesUpdateRequest) SetNvLinkPartitionNil() {
	o.NvLinkPartition.Set(nil)
}

// UnsetNvLinkPartition ensures that no value is present for NvLinkPartition, not even an explicit nil
func (o *SiteCapabilitiesUpdateRequest) UnsetNvLinkPartition() {
	o.NvLinkPartition.Unset()
}

// GetFlow returns the Flow field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SiteCapabilitiesUpdateRequest) GetFlow() bool {
	if o == nil || IsNil(o.Flow.Get()) {
		var ret bool
		return ret
	}
	return *o.Flow.Get()
}

// GetFlowOk returns a tuple with the Flow field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SiteCapabilitiesUpdateRequest) GetFlowOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Flow.Get(), o.Flow.IsSet()
}

// HasFlow returns a boolean if a field has been set.
func (o *SiteCapabilitiesUpdateRequest) HasFlow() bool {
	if o != nil && o.Flow.IsSet() {
		return true
	}

	return false
}

// SetFlow gets a reference to the given NullableBool and assigns it to the Flow field.
func (o *SiteCapabilitiesUpdateRequest) SetFlow(v bool) {
	o.Flow.Set(&v)
}

// SetFlowNil sets the value for Flow to be an explicit nil
func (o *SiteCapabilitiesUpdateRequest) SetFlowNil() {
	o.Flow.Set(nil)
}

// UnsetFlow ensures that no value is present for Flow, not even an explicit nil
func (o *SiteCapabilitiesUpdateRequest) UnsetFlow() {
	o.Flow.Unset()
}

// GetImageBasedOperatingSystem returns the ImageBasedOperatingSystem field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SiteCapabilitiesUpdateRequest) GetImageBasedOperatingSystem() bool {
	if o == nil || IsNil(o.ImageBasedOperatingSystem.Get()) {
		var ret bool
		return ret
	}
	return *o.ImageBasedOperatingSystem.Get()
}

// GetImageBasedOperatingSystemOk returns a tuple with the ImageBasedOperatingSystem field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SiteCapabilitiesUpdateRequest) GetImageBasedOperatingSystemOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.ImageBasedOperatingSystem.Get(), o.ImageBasedOperatingSystem.IsSet()
}

// HasImageBasedOperatingSystem returns a boolean if a field has been set.
func (o *SiteCapabilitiesUpdateRequest) HasImageBasedOperatingSystem() bool {
	if o != nil && o.ImageBasedOperatingSystem.IsSet() {
		return true
	}

	return false
}

// SetImageBasedOperatingSystem gets a reference to the given NullableBool and assigns it to the ImageBasedOperatingSystem field.
func (o *SiteCapabilitiesUpdateRequest) SetImageBasedOperatingSystem(v bool) {
	o.ImageBasedOperatingSystem.Set(&v)
}

// SetImageBasedOperatingSystemNil sets the value for ImageBasedOperatingSystem to be an explicit nil
func (o *SiteCapabilitiesUpdateRequest) SetImageBasedOperatingSystemNil() {
	o.ImageBasedOperatingSystem.Set(nil)
}

// UnsetImageBasedOperatingSystem ensures that no value is present for ImageBasedOperatingSystem, not even an explicit nil
func (o *SiteCapabilitiesUpdateRequest) UnsetImageBasedOperatingSystem() {
	o.ImageBasedOperatingSystem.Unset()
}

func (o SiteCapabilitiesUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SiteCapabilitiesUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.NativeNetworking.IsSet() {
		toSerialize["nativeNetworking"] = o.NativeNetworking.Get()
	}
	if o.NetworkSecurityGroup.IsSet() {
		toSerialize["networkSecurityGroup"] = o.NetworkSecurityGroup.Get()
	}
	if o.NvLinkPartition.IsSet() {
		toSerialize["nvLinkPartition"] = o.NvLinkPartition.Get()
	}
	if o.Flow.IsSet() {
		toSerialize["flow"] = o.Flow.Get()
	}
	if o.ImageBasedOperatingSystem.IsSet() {
		toSerialize["imageBasedOperatingSystem"] = o.ImageBasedOperatingSystem.Get()
	}
	return toSerialize, nil
}

type NullableSiteCapabilitiesUpdateRequest struct {
	value *SiteCapabilitiesUpdateRequest
	isSet bool
}

func (v NullableSiteCapabilitiesUpdateRequest) Get() *SiteCapabilitiesUpdateRequest {
	return v.value
}

func (v *NullableSiteCapabilitiesUpdateRequest) Set(val *SiteCapabilitiesUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSiteCapabilitiesUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSiteCapabilitiesUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSiteCapabilitiesUpdateRequest(val *SiteCapabilitiesUpdateRequest) *NullableSiteCapabilitiesUpdateRequest {
	return &NullableSiteCapabilitiesUpdateRequest{value: val, isSet: true}
}

func (v NullableSiteCapabilitiesUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSiteCapabilitiesUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
