#
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# This is the global configuration file for nico-api that is shared
# between all environments.
# Each environment can overwrite certain parameters of this file via a
# nico-api-site-config.toml file. Those are placed in the `envs/` folder
# for the respective environment

listen = "[::]:1079"
metrics_endpoint = "[::]:1080"
profiler_endpoint = "[::]:1081"
database_url = "postgres://replaced-by-env-var"
asn = 4294967000
initial_dpu_agent_upgrade_policy = "up_only"
dpu_nic_firmware_intial_update_enabled = false
dpu_nic_firmware_reprovision_update_enabled = true
dpu_nic_firmware_update_version = { "BlueField SoC" = "24.42.1000", "BlueField-3 SmartNIC Main Card" = "32.42.1000" }
max_concurrent_machine_updates = 10
nvue_enabled = true
dhcp_servers = []                                                                                                     # Added in per-site-configuration
route_servers = []                                                                                                    # Required for FNN. Not yet used
attestation_enabled = true
bypass_rbac = true

[host_health]
hardware_health_reports = "MonitorOnly"

[site_explorer]
enabled = true
create_machines = true

[firmware_global]
autoupdate = true

[machine_identity]
enabled = true
current_encryption_key_id = "kv1" # must match a key under machine_identity.encryption_keys in credentials
algorithm = "ES256" # must match tenant identity signing alg (ES256 only)

[tls]
identity_pemfile_path = "/var/run/secrets/spiffe.io/tls.crt"
identity_keyfile_path = "/var/run/secrets/spiffe.io/tls.key"
root_cafile_path = "/var/run/secrets/spiffe.io/ca.crt"
admin_root_cafile_path = "/etc/nico/nico-api/site/admin_root_cert_pem"

[auth]
permissive_mode = false
casbin_policy_file = "/etc/nico/nico-api/casbin-policy.csv"

[machine_state_controller]
failure_retry_time = "90m"

[network_security_group]
# Controls whether additional config to support
# stateful/reflexive ACLs will be inserted into
# the HBN config.
# This is expected to remain off at least until all sites
# are running HBN 2.3 or higher.  The reflexive-acl
# implementation in earlier versions exposes a way for
# users to accidentally permit-all in both directions
# with a single rule in one direction.
stateful_acls_enabled = false

# Maximum number of security groups rules
# after they are expanded:
# src port range * dst port range * src prefix list * dst prefix list
# NOTE: There is also a hard-limit in the
# DPU agent of 10k (as of the time of this
# comment) to protect it misconfig in
# site-controller.
max_network_security_group_size = 200

# Enable Machine Validation feature and enable all tests
[machine_validation_config]
enabled = true
test_selection_mode = "EnableAll"
